// Generated by CoffeeScript 1.6.3
jQuery(document).ready(function() {
  $('.js-project-link').on('click', function(e) {
    var href, target;
    e.preventDefault();
    target = $(this).data('target');
    href = "#" + target;
    $("#" + target).fadeIn().addClass('js-active-project');
    return $(document).scrollTop(0);
  });
  return $('.close').on('click', function(e) {
    e.preventDefault();
    return $('.js-active-project').fadeOut().removeClass('js-active-project');
  });
});
